name: Test GitHub expressions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Useufll links:
  # [Events that trigger workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)
  # [About pull requests](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request)
  # [Github Expressions](https://docs.github.com/en/actions/learn-github-actions/expressions)

  IS_RELEASE_CANDIDATE: |
    ${{
      contains(fromJSON('["push", "pull_request"]'), github.event_name) &&
      startsWith(github.event.pull_request.title, 'RELEASES:') &&
      contains(github.event.pull_request.labels.*.name, 'RELEASES')
    }}

jobs:
  test-variable:
    runs-on: ubuntu-latest
    steps:
      - name: contains(fromJSON('["push", "pull_request"]'), github.event_name)
        run: echo ${{ contains(fromJSON('["push", "pull_request"]'), github.event_name) }}
      - name: startsWith(github.event.pull_request.title, 'RELEASES:')
        run: echo ${{ startsWith(github.event.pull_request.title, 'RELEASES:') }}
      - name: startsWith(github.event.head_commit.title, 'RELEASES:')
        run: echo ${{ startsWith(github.event.head_commit.message, 'RELEASES:') }}
      - name: contains(github.event.pull_request.labels.*.name, 'RELEASES')
        if: contains(github.event.pull_request.labels.*.name, 'RELEASES')
        run: echo ${{ contains(github.event.pull_request.labels.*.name, 'RELEASES') }}
      - name: env.IS_RELEASE_CANDIDATE
        run: echo ${{ env.IS_RELEASE_CANDIDATE }}
